import { PROTOCOL_CONSTANTS } from "../src/constants/lend";

// WHEN OUTPUT TOKEN IS NOT SAME AS ASSET, WILL ACTIVATE JUP SWAP
export const outputMintAddress = "";
export const outputTokenProgram = "";

export const depositStrategyAmount = -1;
export const withdrawStrategyAmount = -1;

export const jupSwapSlippageBps = 50; // 0.5%
export const jupSwapMaxAccounts = 16;

// SOLEND VARIABLES: ONLY MAIN MARKET SUPPORTED, CHANGE AND ALIGN TO OUTPUT TOKEN
export const solendCounterpartyTa =
  PROTOCOL_CONSTANTS.SOLEND.MAIN_MARKET.USDC.COUNTERPARTY_TA;
export const solendCollateralMint =
  PROTOCOL_CONSTANTS.SOLEND.MAIN_MARKET.USDC.COLLATERAL_MINT;
export const solendReserve = PROTOCOL_CONSTANTS.SOLEND.MAIN_MARKET.USDC.RESERVE;
export const solendPythOracle =
  PROTOCOL_CONSTANTS.SOLEND.MAIN_MARKET.USDC.PYTH_ORACLE;
export const solendSwitchboardOracle =
  PROTOCOL_CONSTANTS.SOLEND.MAIN_MARKET.USDC.SWITCHBOARD_ORACLE;

// MARGINFI VARIABLES: ONLY MAIN MARKET SUPPORTED, CHANGE AND ALIGN TO OUTPUT TOKEN
export const marginfiBank = PROTOCOL_CONSTANTS.MARGINFI.MAIN_MARKET.USDC.BANK;
export const marginfiAccount = ""; // FILL UP AFTER INITIALIZING MARGINFI
export const marginfiOracle =
  PROTOCOL_CONSTANTS.MARGINFI.MAIN_MARKET.USDC.ORACLE;

// KLEND VARIABLES: SUPPORTS MULTIPLE MARKETS, CHANGE AND ALIGN TO OUTPUT TOKEN
export const klendLendingMarket =
  PROTOCOL_CONSTANTS.KLEND.MAIN_MARKET.LENDING_MARKET;
export const klendReserve = PROTOCOL_CONSTANTS.KLEND.MAIN_MARKET.USDC.RESERVE;

// DRIFT VARIABLES: ONLY MAIN MARKET SUPPORTED, CHANGE AND ALIGN TO OUTPUT TOKEN
export const driftMarketIndex = PROTOCOL_CONSTANTS.DRIFT.SPOT.USDC.MARKET_INDEX;
export const driftOracle = PROTOCOL_CONSTANTS.DRIFT.SPOT.USDC.ORACLE;
